- name: Demo on simple playbook
  hosts: all
  vars:
    a: 100
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task1'
    - name: Task2
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task2 - {{a}}'

